name: NodeJS CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Uses Node.JS
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: yarn install

      - name: Cleans dist directory
        run: node clear.js

      - name: Compile TypeScript
        run: tsc

      - name: Cleans dist directory again
        run: node clear.js